package(default_visibility = ['//visibility:public'])

load("@rules_cc//cc:defs.bzl", "cc_binary")

# --------------------------------------------------------
# Hello world

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)
