name: Main
on:
    push:
        branches-ignore:
            - 'renovate/*'
    pull_request:
        branches:
            - 'main'

jobs:
    name: Hello World
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - run: bazel build //test:hello-world
      
